#' Composer data from Open Opus
#'
#' Sample output of composer information generated by [get_oo_composers()].
#'
#' @format ## `oo_composers`
#' A data frame with the following columns:
#' \describe{
#'   \item{complete_name}{Name of the composer}
#'   \item{epoch}{Classical music era}
#'   \item{birth}{Birth year of the composer}
#'   \item{death}{Death year of the composer}
#' }
#' @source [Open Opus API](https://github.com/openopus-org/openopus_api)
"oo_composers"