#' Raw metadata of tracks in a Spotify playlist
#'
#' Sample output of raw track metadata generated by `get_track_metadata().
#'
#' @format ## `track_metadata_raw`
#' A data frame with 114 rows and 40 columns. 
#' 
#' @source Spotify API
"track_metadata_raw"