#' Metadata of tracks in a Spotify playlist
#'
#' Sample output of cleaned track metadata generated by [clean_track_metadata()].
#'
#' @format ## `track_metadata`
#' A data frame with the following columns:
#' \describe{
#'   \item{url}{External Spotify URL of track}
#'   \item{artist}{Concatenated artist names}
#'   \item{year}{Release year of track}
#'   \item{track_name}{Name of track}
#' }
#' @source Spotify API
"track_metadata"