#' Metadata of tracks in a Spotify playlist
#'
#' Sample output of cleaned track metadata generated by `clean_track_metadata().
#'
#' @format ## `track_metadata`
#' A data frame with 114 rows and 5 columns:
#' \describe{
#'   \item{artist1, artist}{First artist & first two artists concatenated}
#'   \item{year}{Release year of track}
#'   \item{track_name}{Name of track}
#'   \item{url}{External Spotify URL of track}
#' }
#' @source Spotify API
"track_metadata"